# Generated by Django 5.2 on 2025-04-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description du produit')),
                ('urlImage', models.TextField(verbose_name='Description du produit')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix du produit')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('quantite', models.IntegerField(verbose_name='Quantite')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Ecomming.categorie')),
            ],
        ),
    ]
