# Generated by Django 5.2 on 2025-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='urlImage',
            field=models.TextField(verbose_name="URL de l'image du produit"),
        ),
    ]
