# Generated by Django 5.2 on 2025-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0002_alter_produit_urlimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='disponible',
        ),
    ]
