# Generated by Django 5.2 on 2025-04-12 07:30

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0007_photo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='urlImage',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
