# Generated by Django 5.2 on 2025-04-13 10:12

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0008_remove_produit_urlimage_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='produit',
            name='image_couverture',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image_couverture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_produit', to='Ecomming.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='produits_associes', to='Ecomming.imageproduit'),
        ),
    ]
