# Generated by Django 5.2 on 2025-04-13 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0009_imageproduit_delete_photo_remove_produit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduit',
            name='produit',
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='imageproduit',
            name='titre',
            field=models.CharField(blank=True, max_length=100, verbose_name="Titre de l'image"),
        ),
    ]
