# Generated by Django 5.2 on 2025-04-13 10:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0010_remove_imageproduit_produit_imageproduit_date_ajout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='images',
        ),
        migrations.AddField(
            model_name='produit',
            name='image_1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_couverture'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_couverture'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_couverture'),
        ),
    ]
