# Generated by Django 5.2 on 2025-04-13 10:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0011_remove_produit_images_produit_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_3'),
        ),
    ]
