# Generated by Django 5.2 on 2025-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomming', '0012_alter_produit_image_1_alter_produit_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('description_entreprise', models.TextField()),
            ],
        ),
    ]
